name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-without-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          echo: "Hello world "
      - uses: ./download-syft # anchore/sbom-action/download-syft
        id: syft

      - run: |
          echo "${{ steps.syft.outputs.cmd }}"
          "${{ steps.syft.outputs.cmd }}" dir:.
      - uses: ./ # anchore/sbom-action
        id: dirscan
        with:
          artifact-name: sbom.spdx
          output-file: dirscan-sbom.spdx
          format: spdx
      - run: |
          echo DIR SCAN SBOM:
          cat dirscan-sbom.spdx
      - uses: ./ # anchore/sbom-action
        id: imagescan
        with:
          image: alpine:latest
          artifact-name: sbom.spdx
          output-file: my.sbom
      - run: |
          echo IMAGE SCAN SBOM:
          cat my.sbom
      - uses: ./publish-sbom # anchore/sbom-action/publish-sbom
        with:
          sbom-artifact-match: sbom.spdx

      - uses: ./publish-sbom # anchore/sbom-action/publish-sbom
        with:
          sbom-artifact-match: "^dont-match-anything$"
