name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-without-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          echo: "Hello world "
      - name: Anchore SBOM Action
        uses: anchore/sbom-action@v0.6.0
        with:
          artifact-name: sbom.spdx
